[package]
name = "mrcc-lex"
version = "0.1.0"
authors = ["Noam Raz <noamraz8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mrcc-source = { path = "../mrcc-source" }
intern = { path = "../intern" }
